### PR TITLE
migration of Clustering interface to MLJClusteringInterface.jl

### PR DESCRIPTION
**Pull request by OkonSamuel**
#244  #311 https://github.com/alan-turing-institute/MLJClusteringInterface.jl/issues/2

### CODE REVIEW

**Comment by ablaom** [comment]
@OkonSamuel Did you fore a recompile and run `MLJModels.check_registry()` successfully?

**Comment by OkonSamuel** [comment]
I forced a recompile. But don't have enough time to wait for
`MLJModels.check_registry` to complete.

**Comment by OkonSamuel** [comment]
I forced a recompile. But don't have enough time to wait for `MLJModels.check_registry` to complete.

**Comment by OkonSamuel** [comment]
@ablaom `MLJModels.check_registry`  ran successfully with no errors.

**Pull request merged**
