### PR TITLE
Revert "Utilsmigration" take 2

### PR DESCRIPTION
**Pull request by ablaom**
This is a new PR to merge the contents of the utilsmigration branch onto master.

### CODE REVIEW

**Comment by ablaom** [comment]
@tlienart When I tested the utilsmigration branch locally, with MLJBase#dev (now a pending tagged release 0.6.0) I had some problems (julia 1.0.5 and 1.2; haven't tested others). 

Did some other merges onto dev happen after you tested?

Maybe easier to diagnose after MLJBase 0.6.0 is released.

```julia
julia> Pkg.status()
    Status `~/Dropbox/Julia7/MLJ/MLJModels/sandbox/junk/Project.toml`
  [a7f614a8] MLJBase v0.6.0 #dev (https://github.com/alan-turing-institute/MLJBase.jl.git)
  [d491faf4] MLJModels v0.4.0 #utilsmigration (https://github.com/alan-turing-institute/MLJModels.jl.git)

(junk) pkg> test MLJModels
   Testing MLJModels
 Resolving package versions...
    Status `/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/tmpUKR73h/Manifest.toml`
  [621f4979] AbstractFFTs v0.4.1
  [7d9fca2a] Arpack v0.3.1
  [4fba245c] ArrayInterface v1.2.1
  [13072b0f] AxisAlgorithms v1.0.0
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.6
  [a74b3585] Blosc v0.5.1
  [631607c0] CMake v1.1.2
  [d5fb7624] CMakeWrapper v0.2.3
  [00ebfdb7] CSTParser v0.6.2
  [336ed68f] CSV v0.5.12
  [49dc2e85] Calculus v0.5.0
  [324d7699] CategoricalArrays v0.5.2
  [aaaa29a8] Clustering v0.13.3
  [944b1d66] CodecZlib v0.5.2
  [3da002f7] ColorTypes v0.8.0
  [5ae59095] Colors v0.9.6
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [8f4d0f93] Conda v1.3.0
  [9a962f9c] DataAPI v1.0.1
  [a93c6f00] DataFrames v0.18.4
  [864edb3b] DataStructures v0.17.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [7806a523] DecisionTree v0.8.3
  [01453d9d] DiffEqDiffTools v1.3.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [b4f34e82] Distances v0.8.2
  [31c24e10] Distributions v0.21.1
  [fdbdab4c] ElasticArrays v0.4.0
  [2904ab23] ElasticPDMats v0.2.1
  [8f5d6c58] EzXML v0.9.4
  [7a1cc6ca] FFTW v0.3.0
  [442a2c76] FastGaussQuadrature v0.4.0
  [5789e2e9] FileIO v1.0.7
  [1a297f60] FillArrays v0.7.0
  [53c48c17] FixedPointNumbers v0.6.1
  [f6369f11] ForwardDiff v0.10.3
  [38e38edf] GLM v1.3.2
  [cc18c42c] GaussianMixtures v0.3.0
  [891a1506] GaussianProcesses v0.9.0
  [f67ccb44] HDF5 v0.12.3
  [a98d9a8b] Interpolations v0.12.2
  [c8e1da08] IterTools v1.2.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [4138dd39] JLD v0.9.1
  [682c06a0] JSON v0.21.0
  [5ab0869b] KernelDensity v0.5.1
  [2d691ee1] LIBLINEAR v0.5.1
  [b1bec4e5] LIBSVM v0.3.1
  [b964fa9f] LaTeXStrings v1.0.3
  [1b4a561d] LegacyStrings v0.4.1
  [d3d80556] LineSearches v7.0.1
  [a7f614a8] MLJBase v0.6.0 #dev (https://github.com/alan-turing-institute/MLJBase.jl.git)
  [d491faf4] MLJModels v0.4.0 #utilsmigration (https://github.com/alan-turing-institute/MLJModels.jl.git)
  [1914dd2f] MacroTools v0.5.1
  [e1d29d7a] Missings v0.4.2
  [78c3b35d] Mocking v0.7.0
  [6f286f6a] MultivariateStats v0.7.0
  [0db19996] NBInclude v2.1.0
  [d41bc354] NLSolversBase v7.4.1
  [77ba4419] NaNMath v0.3.2
  [9bbee03b] NaiveBayes v0.4.0
  [b8a86587] NearestNeighbors v0.4.3
  [6fe1bfb0] OffsetArrays v0.11.1
  [429524aa] Optim v0.19.3
  [bac558e1] OrderedCollections v1.1.0
  [90014a1f] PDMats v0.9.10
  [d96e819e] Parameters v0.12.0
  [69de0a69] Parsers v0.3.7
  [2dfb63ee] PooledArrays v0.5.2
  [85a6dd25] PositiveFactorizations v0.2.2
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.2
  [1fd47b50] QuadGK v2.0.3
  [df47a6cb] RData v0.6.3
  [ce6b1742] RDatasets v0.6.3
  [c84ed2f1] Ratios v0.3.1
  [3cdcf5f2] RecipesBase v0.7.0
  [731186ca] RecursiveArrayTools v0.18.6
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [79098fc4] Rmath v0.5.0
  [321657f4] ScientificTypes v0.2.0
  [3646fa90] ScikitLearn v0.5.1
  [6e75b9c4] ScikitLearnBase v0.5.0
  [1277b4bf] ShiftedArrays v0.5.0
  [b85f4697] SoftGlobalScope v1.0.10
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.11.0
  [2913bbd2] StatsBase v0.32.0
  [4c63d2b9] StatsFuns v0.8.0
  [3eaba693] StatsModels v0.6.3
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v0.2.11
  [f269a46b] TimeZones v0.10.0
  [0796e94c] Tokenize v0.5.6
  [3bb67fe8] TranscodingStreams v0.9.5
  [30578b45] URIParser v0.4.0
  [81def892] VersionParsing v1.1.3
  [ea10d353] WeakRefStrings v0.6.1
  [efce3f68] WoodburyMatrices v0.4.1
  [009559a3] XGBoost v0.4.1
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [9fa8497b] Future  [`@stdlib/Future`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [4607b0f0] SuiteSparse  [`@stdlib/SuiteSparse`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
[ Info: Model metadata loaded from registry. 
[ Info: MLJModels.Constant.ConstantRegressor
import MLJModels ✔
import DecisionTree ✔
import MLJModels.DecisionTree_.DecisionTreeClassifier ✔
Test Summary: | Pass  Total
metadata      |   48     48
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = catvaluetype at array.jl:555 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/ucKV2/src/array.jl:555
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = catvaluetype at array.jl:555 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/ucKV2/src/array.jl:555
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = catvaluetype at array.jl:555 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/ucKV2/src/array.jl:555
[ Info: Spawning 3 sub-features to one-hot encode feature :favourite_number.
Test Summary:   | Pass  Total
built-in models |   40     40
Test Summary:       | Pass  Total
MultivariateStats   |    7      7
virginica : 50/150
Test Summary:       | Pass  Total
DecisionTree        |    7      7
Test Summary:       | Pass  Total
GaussianProcesses   |    3      3
Test Summary:       | Pass  Total
Clustering          |   15     15
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = catvaluetype at array.jl:555 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/ucKV2/src/array.jl:555
Test Summary:       | Pass  Total
GLM                 |   16     16
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = catvaluetype at array.jl:555 [inlined]
└ @ Core ~/.julia/packages/CategoricalArrays/ucKV2/src/array.jl:555
LogRegClf: Error During Test at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:4
  Got exception outside of a @test
  PyError ($(Expr(:escape, :(ccall(#= /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:44 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
  TypeError("__init__() got an unexpected keyword argument 'l1_ratio'")
  
  Stacktrace:
   [1] pyerr_check at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:60 [inlined]
   [2] pyerr_check at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:64 [inlined]
   [3] macro expansion at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:84 [inlined]
   [4] __pycall!(::PyCall.PyObject, ::Ptr{PyCall.PyObject_struct}, ::PyCall.PyObject, ::PyCall.PyObject) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:44
   [5] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{}, ::Int64, ::PyCall.PyObject) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:29
   [6] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{}, ::Base.Iterators.Pairs{Symbol,Any,NTuple{15,Symbol},NamedTuple{(:penalty, :dual, :tol, :C, :fit_intercept, :intercept_scaling, :class_weight, :random_state, :solver, :max_iter, :multi_class, :verbose, :warm_start, :n_jobs, :l1_ratio),Tuple{String,Bool,Float64,Float64,Bool,Float64,Nothing,Nothing,String,Int64,String,Int64,Bool,Nothing,Nothing}}}) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:11
   [7] #call#111 at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:89 [inlined]
   [8] (::getfield(PyCall, Symbol("#kw#PyObject")))(::NamedTuple{(:penalty, :dual, :tol, :C, :fit_intercept, :intercept_scaling, :class_weight, :random_state, :solver, :max_iter, :multi_class, :verbose, :warm_start, :n_jobs, :l1_ratio),Tuple{String,Bool,Float64,Float64,Bool,Float64,Nothing,Nothing,String,Int64,String,Int64,Bool,Nothing,Nothing}}, ::PyCall.PyObject) at ./none:0
   [9] fit(::MLJModels.ScikitLearn_.LogisticClassifier, ::Int64, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/src/ScikitLearn/ScikitLearn.jl:80
   [10] #simple_test_classif_prob#9(::Bool, ::Bool, ::Float64, ::Function, ::MLJModels.ScikitLearn_.LogisticClassifier, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/testutils.jl:107
   [11] simple_test_classif_prob(::MLJModels.ScikitLearn_.LogisticClassifier, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/testutils.jl:107
   [12] macro expansion at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:5 [inlined]
   [13] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [14] top-level scope at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:5
   [15] include at ./boot.jl:317 [inlined]
   [16] include_relative(::Module, ::String) at ./loading.jl:1044
   [17] include at ./sysimg.jl:29 [inlined]
   [18] include(::String) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/ScikitLearn.jl:1
   [19] top-level scope at none:0
   [20] include at ./boot.jl:317 [inlined]
   [21] include_relative(::Module, ::String) at ./loading.jl:1044
   [22] include(::Module, ::String) at ./sysimg.jl:29
   [23] include(::String) at ./client.jl:392
   [24] macro expansion at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/runtests.jl:57 [inlined]
   [25] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [26] top-level scope at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/runtests.jl:57
   [27] include at ./boot.jl:317 [inlined]
   [28] include_relative(::Module, ::String) at ./loading.jl:1044
   [29] include(::Module, ::String) at ./sysimg.jl:29
   [30] include(::String) at ./client.jl:392
   [31] top-level scope at none:0
   [32] eval(::Module, ::Any) at ./boot.jl:319
   [33] exec_options(::Base.JLOptions) at ./client.jl:243
   [34] _start() at ./client.jl:425
LogRegCVClf: Error During Test at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:14
  Got exception outside of a @test
  PyError ($(Expr(:escape, :(ccall(#= /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:44 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
  TypeError("__init__() got an unexpected keyword argument 'l1_ratios'")
  
  Stacktrace:
   [1] pyerr_check at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:60 [inlined]
   [2] pyerr_check at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:64 [inlined]
   [3] macro expansion at /Users/anthony/.julia/packages/PyCall/ttONZ/src/exception.jl:84 [inlined]
   [4] __pycall!(::PyCall.PyObject, ::Ptr{PyCall.PyObject_struct}, ::PyCall.PyObject, ::PyCall.PyObject) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:44
   [5] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{}, ::Int64, ::PyCall.PyObject) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:29
   [6] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{}, ::Base.Iterators.Pairs{Symbol,Any,NTuple{17,Symbol},NamedTuple{(:Cs, :fit_intercept, :cv, :dual, :penalty, :scoring, :solver, :tol, :max_iter, :class_weight, :n_jobs, :verbose, :refit, :intercept_scaling, :multi_class, :random_state, :l1_ratios),Tuple{Int64,Bool,Int64,Bool,String,Nothing,String,Float64,Int64,Nothing,Nothing,Int64,Bool,Float64,String,Nothing,Nothing}}}) at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:11
   [7] #call#111 at /Users/anthony/.julia/packages/PyCall/ttONZ/src/pyfncall.jl:89 [inlined]
   [8] (::getfield(PyCall, Symbol("#kw#PyObject")))(::NamedTuple{(:Cs, :fit_intercept, :cv, :dual, :penalty, :scoring, :solver, :tol, :max_iter, :class_weight, :n_jobs, :verbose, :refit, :intercept_scaling, :multi_class, :random_state, :l1_ratios),Tuple{Int64,Bool,Int64,Bool,String,Nothing,String,Float64,Int64,Nothing,Nothing,Int64,Bool,Float64,String,Nothing,Nothing}}, ::PyCall.PyObject) at ./none:0
   [9] fit(::MLJModels.ScikitLearn_.LogisticCVClassifier, ::Int64, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/src/ScikitLearn/ScikitLearn.jl:80
   [10] #simple_test_classif_prob#9(::Bool, ::Bool, ::Float64, ::Function, ::MLJModels.ScikitLearn_.LogisticCVClassifier, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/testutils.jl:107
   [11] simple_test_classif_prob(::MLJModels.ScikitLearn_.LogisticCVClassifier, ::Tables.MatrixTable{Array{Float64,2}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/testutils.jl:107
   [12] macro expansion at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:15 [inlined]
   [13] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [14] top-level scope at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/linear-classifiers.jl:15
   [15] include at ./boot.jl:317 [inlined]
   [16] include_relative(::Module, ::String) at ./loading.jl:1044
   [17] include at ./sysimg.jl:29 [inlined]
   [18] include(::String) at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/ScikitLearn/ScikitLearn.jl:1
   [19] top-level scope at none:0
   [20] include at ./boot.jl:317 [inlined]
   [21] include_relative(::Module, ::String) at ./loading.jl:1044
   [22] include(::Module, ::String) at ./sysimg.jl:29
   [23] include(::String) at ./client.jl:392
   [24] macro expansion at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/runtests.jl:57 [inlined]
   [25] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [26] top-level scope at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/runtests.jl:57
   [27] include at ./boot.jl:317 [inlined]
   [28] include_relative(::Module, ::String) at ./loading.jl:1044
   [29] include(::Module, ::String) at ./sysimg.jl:29
   [30] include(::String) at ./client.jl:392
   [31] top-level scope at none:0
   [32] eval(::Module, ::Any) at ./boot.jl:319
   [33] exec_options(::Base.JLOptions) at ./client.jl:243
   [34] _start() at ./client.jl:425
Test Summary:       | Pass  Error  Total
ScikitLearn         |  262      2    264
  SVM-infos         |    7             7
  SVCs              |    3             3
  SVRs              |    3             3
  ARD               |    3             3
  BayesianRidge     |    3             3
  ElasticNet        |    3             3
  ElasticNetCV      |    3             3
  Huber             |    3             3
  Lars              |    3             3
  LarsCV            |    3             3
  Lasso             |    3             3
  LassoCV           |    3             3
  LassoLars         |    3             3
  LassoLarsCV       |    3             3
  LassoLarsIC       |    3             3
  LinReg            |    5             5
  OMP               |    3             3
  OMPCV             |    3             3
  OMPCV             |    3             3
  PassAggr          |    3             3
  RANSAC            |    3             3
  Ridge             |    3             3
  RidgeCV           |    4             4
  SGDReg            |    3             3
  TheilSen          |    3             3
  MTLassoCV         |    4             4
  MTLassoCV         |    3             3
  MTElNet           |    3             3
  MTElNetCV         |    3             3
  LogRegClf         |           1      1
  LogRegCVClf       |           1      1
  PAClf             |    7             7
  PerceptronClf     |    7             7
  RidgeClf          |    7             7
  RidgeCVClf        |    7             7
  SGDClf            |   13            13
  GPRegressor       |    3             3
  GPClassif         |    8             8
  AdaBoostReg       |    3             3
  BaggingReg        |    3             3
  XTreeReg          |    3             3
  GBReg             |    3             3
  RFReg             |    3             3
  AdaboostClf       |    8             8
  BaggingClf        |    8             8
  GradBoostClf      |    8             8
  RForestClf        |    8             8
  XTreeClf          |    8             8
  DummyReg          |    4             4
  DummyClf          |    7             7
  GaussianNBClf     |    8             8
  KNNReg            |    5             5
  KNNClf            |    8             8
  BernNBClf         |    7             7
  MultiNBClf        |    7             7
  ComplNBClf        |    7             7
ERROR: LoadError: Some tests did not pass: 262 passed, 0 failed, 2 errored, 0 broken.
in expression starting at /Users/anthony/.julia/packages/MLJModels/0i1tm/test/runtests.jl:56
ERROR: Package MLJModels errored during testing
```

**Comment by tlienart** [comment]
my dev branches were in synch so not sure what you're experiencing. But let's wait for MLJBase  0.6 to be tagged

**Comment by ablaom** [comment]
There are clean! methods in src/NearestNeighbors.jl. I guesss these are redundant since the @sk_macro generates clean! ? (If I remove, then I get rid of some bugs that crash MLJ tests.)

**Comment by tlienart** [comment]
this is now superseded by #72

**Pull request closed without merging**
