### PR TITLE
Add interactive version of `@load`

### LINKED ISSUE #348: Add an interactive version of @load
See the discussion at #346

### PR DESCRIPTION
**Pull request by ablaom**
Here called `@iload`. This resolves #348.

Also resolves minor bug #353.

User is called to interact whenever:

- The model specified appears in multiple packages (and user has not specified pkg=...); user chooses which package is desired
- The model name is already in scope (generally because a model of the same name has been loaded from a different package); user chooses to go with auto-generated name or is invited to choose a new one (checked for validity)
- The package providing the interface for the model is not in the user's environment; the user is asked to confirm installation or abort (installation is automatic if `install=true` is specified)

### CODE REVIEW

**Comment by ablaom** [comment]
### Review notes

I'm not sure how to add testing for a user-interactive function and have not included testing in this PR.

It would therefore be good to get a more thorough review for this, if possible. To this end, in testing interactively, it is useful to note that three packages all provide a model type called `KMeans`.

So one might try `@iload KMeans` and respond in different ways, starting perhaps  with a environment with just `MLJModels` in it.

**Comment by ablaom** [comment]
@DilumAluthge As you are already familiar with this code, be great if you can take a look.

cc @ExpandingMan

**Comment by DilumAluthge** [comment]
At what time are you calling the `request` function? It looks to me like you are calling it at macro expansion time, which seems incorrect to me. Instead of calling the `request` function inside the body of the macro, the macro should return an expression, and the call to the `request` function should be inside that expression.

**Comment by ablaom** [comment]
@DilumAluthge Many belated thanks for the review. Yes you are correct in that some of the `request` calls were not wrapped in the returned expression. 

Closing in favour of #358

**Pull request closed without merging**
