### PR TITLE
Add the `GenericGLMModel` model type

### PR DESCRIPTION
**Pull request by DilumAluthge**
The current implementation of GLM.jl models in MLJModels.jl has several limitations:
1. It fits the models by passing matrices `X` and `y` to GLM.jl. Because of this, GLM.jl does not know the names of the feature columns. Therefore, when you look at the `fitresult`, the feature column names are `x1`, `x2`, `x3`. This is suboptimal, because it makes it difficult and inconvenient to figure out which coefficient goes with which feature columns. If GLM.jl is given an appropriate tabular data structure (e.g. a `DataFrame`), then it will assign the correct names to each coefficient.
2. It does not accept a `StatsModels.@formula`. Formulas are a very useful way to e.g. add interaction terms to a GLM.

This pull request adds the `GenericGLMModel` model, which seeks to overcome these limitations. 

In particular, the advantages of the `GenericGLMModel` are:
1. It accepts any type of `X` and any type of `y`. It `hcat`s `X` and `y` together, and passes the result to `GLM.glm`. Therefore, if `X` and `y` are `DataFrame`s, then the `fitresult` will have the correct feature names for the coefficients.
2. It accepts any formula. This allows the user to e.g. specify interaction terms.
3. It accepts any distribution.
4. It accepts any link function.

Example usage:

```julia
julia> formula = GLM.@formula(MedV ~ Crim + Zn + Indus + Crim*Zn + Crim*Indus)
FormulaTerm
Response:
  MedV(unknown)
Predictors:
  Crim(unknown)
  Zn(unknown)
  Indus(unknown)
  Crim(unknown) & Zn(unknown)
  Crim(unknown) & Indus(unknown)

julia> distribution = GLM.Normal()
Distributions.Normal{Float64}(μ=0.0, σ=1.0)

julia> link = GLM.IdentityLink()
GLM.IdentityLink()

julia> model = GenericGLMModel(formula, distribution, link)
typename(GenericGLMModel)(
    formula = MedV ~ Crim + Zn + Indus + Crim & Zn + Crim & Indus,
    distribution = Distributions.Normal{Float64}(μ=0.0, σ=1.0),
    link = GLM.IdentityLink()) @464

julia> boston_data = RDatasets.dataset("MASS", "Boston") |> DataFrames.DataFrame;

julia> X = boston_data[!, ["Crim", "Zn", "Indus"]];

julia> y = boston_data[!, ["MedV"]];

julia> fitresult, cache, report = MLJBase.fit(model, 1, X, y)
(StatsModels.TableRegressionModel{GLM.GeneralizedLinearModel{GLM.GlmResp{Vector{Float64},Distributions.Normal{Float64},GLM.IdentityLink},GLM.DensePredChol{Float64,Cholesky{Float64,Matrix{Float64}}}},Matrix{Float64}}

MedV ~ 1 + Crim + Zn + Indus + Crim & Zn + Crim & Indus

Coefficients:
──────────────────────────────────────────────────────────────────────────────
                   Coef.  Std. Error      z  Pr(>|z|)    Lower 95%   Upper 95%
──────────────────────────────────────────────────────────────────────────────
(Intercept)   28.1788      1.07858    26.13    <1e-99   26.0648     30.2927
Crim          -7.20992     2.63361    -2.74    0.0062  -12.3717     -2.04815
Zn             0.0153826   0.0201081   0.76    0.4443   -0.0240286   0.0547938
Indus         -0.466864    0.0738634  -6.32    <1e-9    -0.611634   -0.322095
Crim & Zn      0.784709    0.182376    4.30    <1e-4     0.427258    1.14216
Crim & Indus   0.384885    0.145596    2.64    0.0082    0.0995226   0.670247
──────────────────────────────────────────────────────────────────────────────, nothing, (deviance = 29017.979457077137, dof_residual = 500.0, stderror = [1.0785786143255318, 2.633607652503507, 0.02010812488035706, 0.0738634313149521, 0.18237625399210994, 0.14559561893081874], vcov = [1.163331827280384 -1.6279830602057728 … 0.0007003599327585695 0.09025413807397616; -1.6279830602057728 6.935889267325032 … -0.17491999516139883 -0.38339026963589745; … ; 0.0007003599327585695 -0.17491999516139883 … 0.0332610980201946 0.009670904932838223; 0.09025413807397616 -0.38339026963589745 … 0.009670904932838223 0.021198084251848187]))

julia> fitresult
StatsModels.TableRegressionModel{GLM.GeneralizedLinearModel{GLM.GlmResp{Vector{Float64},Distributions.Normal{Float64},GLM.IdentityLink},GLM.DensePredChol{Float64,Cholesky{Float64,Matrix{Float64}}}},Matrix{Float64}}

MedV ~ 1 + Crim + Zn + Indus + Crim & Zn + Crim & Indus

Coefficients:
──────────────────────────────────────────────────────────────────────────────
                   Coef.  Std. Error      z  Pr(>|z|)    Lower 95%   Upper 95%
──────────────────────────────────────────────────────────────────────────────
(Intercept)   28.1788      1.07858    26.13    <1e-99   26.0648     30.2927
Crim          -7.20992     2.63361    -2.74    0.0062  -12.3717     -2.04815
Zn             0.0153826   0.0201081   0.76    0.4443   -0.0240286   0.0547938
Indus         -0.466864    0.0738634  -6.32    <1e-9    -0.611634   -0.322095
Crim & Zn      0.784709    0.182376    4.30    <1e-4     0.427258    1.14216
Crim & Indus   0.384885    0.145596    2.64    0.0082    0.0995226   0.670247
──────────────────────────────────────────────────────────────────────────────

julia> GLM.coeftable(fitresult)
──────────────────────────────────────────────────────────────────────────────
                   Coef.  Std. Error      z  Pr(>|z|)    Lower 95%   Upper 95%
──────────────────────────────────────────────────────────────────────────────
(Intercept)   28.1788      1.07858    26.13    <1e-99   26.0648     30.2927
Crim          -7.20992     2.63361    -2.74    0.0062  -12.3717     -2.04815
Zn             0.0153826   0.0201081   0.76    0.4443   -0.0240286   0.0547938
Indus         -0.466864    0.0738634  -6.32    <1e-9    -0.611634   -0.322095
Crim & Zn      0.784709    0.182376    4.30    <1e-4     0.427258    1.14216
Crim & Indus   0.384885    0.145596    2.64    0.0082    0.0995226   0.670247
──────────────────────────────────────────────────────────────────────────────

julia> GLM.coeftable(fitresult).rownms
6-element Vector{String}:
 "(Intercept)"
 "Crim"
 "Zn"
 "Indus"
 "Crim & Zn"
 "Crim & Indus"
```

---

If there's a different way to achieve the same result, I'm happy to pursue that instead. My main needs are:
1. The coefficients need to have the correct names, based on the column names in the `DataFrame`.
2. The ability to provide an arbitrary formula.
3. The ability to specify an arbitrary distribution.
4. The ability to specify an arbitrary link function.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
If there's a different way to achieve the same result, I'm happy to pursue that instead. My main needs are:
1. The ability for the coefficients to have the correct names, based on the column names in the `DataFrame`.
2. The ability to provide an arbitrary formula.
3. The ability to specify an arbitrary distribution.
4. The ability to specify an arbitrary link function.

**Comment by ablaom** [comment]
@DilumAluthge Thanks very much for those points and the PR.

These are valid observations but, in short, should be addressed in a different way, in my view.

### Why are there three models and not just one?

MLJ does not provide a single interface to GLM models for the simple reason that different configurations of the base GLM model (different link functions) are generally associated with different *scientific types* of the target. So, instead, we have (currently) three different models, depending on that type: 

```julia
ms = models() do m
       m.package_name =="GLM"
       end
julia> for m in ms
       println(m.name, "\t=>", m.target_scitype)
       end
LinearBinaryClassifier  =>AbstractArray{_s366,1} where _s366<:Finite{2}
LinearCountRegressor    =>AbstractArray{Count,1}
LinearRegressor =>AbstractArray{Continuous,1}

```

(A case missing on this list is `Finite{N}` for `N` bigger than `2`. My view would be to have a new `LinearClassifier` model that includes the `N=2` special case and deprecate the `LinearBinaryClassifier`, to be in line with the tree-boosting models; see below)

Each model has a different `link` default, which makes sense for that model, although I don't believe there is anything stopping you from using an arbitrary link in any model.

This kind of thing has come up elsewhere - for example in the tree-boosting models (eg EvoTrees.jl) and you can probably dig up a fair bit of discussion about this. 

If you have a `link` function choice that does not appear to work please open an issue .

### Specifying a formula

I think it would be great to incorporate the "formula" syntax but I don't think this should be a model-specific thing. Rather, we should just introduce a new transformer that takes a formula as hyper parameter. That is, the transformation of data and the supervised learning parts of the pipeline should be viewed as separate, for greater generality. (However, one problem with the "formula" approach in my view, and from the point of view of the MLJ API, is that it conflates the separation of data into "input" and "target" with other transfomations of that data. I'm not sure if this is still the case in the  StatsBase "formula" API, but I would push for that separation at some level in their API.) If you didn't catch it, check out this talk on `@formula`: https://www.youtube.com/watch?v=lsEv0-TMk5k) but the time is probably right for integration. 

### Outcomes of training, including feature labels

Yes, the labels are missing:

```julia
julia> model = @load LinearBinaryClassifier
LinearBinaryClassifier(
    fit_intercept = true,
    link = GLM.LogitLink()) @267

julia> mach = machine(model, @load_crabs()...) |> fit!;
[ Info: Training Machine{LinearBinaryClassifier{LogitLink}} @990.

julia> report(mach)
(deviance = 3.8893386088094047e-7,
 dof_residual = 195.0,
 stderror = [5422.910452374087, 2527.00616419342, 6810.557077813491, 4442.496211590868, 6031.006332398565, 21416.034740071715],
 vcov = [2.9407957774468128e7 1.0142387761457707e6 … -7.062787418350677e6 4.717937504519563e6; 1.0142387761457707e6 6.385760153871542e6 … -5.648900006710938e6 609425.190452049; … ; -7.062787418350677e6 -5.648900006710938e6 … 3.6373037381431594e7 7.936633808573785e7; 4.717937504519563e6 609425.190452049 … 7.936633808573785e7 4.5864654398795855e8],)

julia> fitted_params(mach)
(coef = [34.633211975760595, 0.6164720504933358, 8.579461070551654, -29.652988093201447, 21.240108906575948],
 intercept = -30.81631266706018,)
```

I assume this is easily fixed for each model. A PR for each of the models above would be most welcome!

### Alternatives to GLM

You may also want to consider the generalised linear models in MLJLinearModels. I understand their performance is generally better and that their `reports/fitted_params` have been recently improved. @tlienart is the author of that package and I'm sure he can steer you in the right direction. 

Does this make sense to you?

Perhaps I missed some of your points - let me know.

**Comment by DilumAluthge** [comment]
Sounds like we have a good roadmap for each of these issues!

**Comment by ablaom** [comment]
Regarding the need to specify arbitrary distributions: There may be some restrictions, eg only `Poisson` for the `Count` regressor. But happy to see a PR to lift any restrictions. If they are likely to cause weird behaviour, we can issue warnings.

**Pull request closed without merging**
