### PR TITLE
Run `MLJModels.check_registry()`, but only on PRs from `dev` into `master`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom This is ready to merge.

Note that the `Check Registry` job only runs if:
1. The job is a pull request job
2. The pull request is NOT being made from a fork
2. The pull request target is `master`
3. The pull request head is `dev`

Therefore, you'll need to merge this PR into `dev`, and then make a PR from `dev` into `master` in order to see the `Check Registry` job in action.

**Comment by DilumAluthge** [comment]
Idk why the regular CI is failing on this PR, but it's unrelated to the contents of the PR.

**Comment by DilumAluthge** [comment]
An example `Check Registry` run is available for viewing here: https://github.com/alan-turing-institute/MLJModels.jl/runs/2198638266

**Comment by DilumAluthge** [comment]
Actually, if you look at https://github.com/alan-turing-institute/MLJModels.jl/runs/2198638266, there are a bunch of errors, e.g.:
```
┌ Error: ⚠ there was an issue trying to load ParallelKMeans.KMeans
└ @ MLJModels ~/work/MLJModels.jl/MLJModels.jl/src/registry/src/check_registry.jl:22
┌ Error: ⚠ there was an issue trying to load NaiveBayes.GaussianNBClassifier
└ @ MLJModels ~/work/MLJModels.jl/MLJModels.jl/src/registry/src/check_registry.jl:22
┌ Error: ⚠ there was an issue trying to load NaiveBayes.MultinomialNBClassifier
└ @ MLJModels ~/work/MLJModels.jl/MLJModels.jl/src/registry/src/check_registry.jl:22
```

But despite that, the command `julia --project -e 'using MLJModels; MLJModels.check_registry()'` exits with status code 0.

@ablaom We would need a way to take the return value of `MLJModels.check_registry()` and throw an exception if there were any errors.

**Comment by ablaom** [comment]
@DilumAluthge Thanks indeed for  this. At a guess the unrelated errors will be addressed by a pending compat update at NaiveBayes already tracked. In the meantime, I could:

- [ ] Get `check_registry()` to throw an exception if error is detected
- [ ] Return something sensible, say a vector of strings of models with issues??

**Comment by DilumAluthge** [comment]
> @DilumAluthge Thanks indeed for this. At a guess the unrelated errors will be addressed by a pending compat update at NaiveBayes already tracked. In the meantime, I could:
> 
>     * [ ]  Get `check_registry()` to throw an exception if error is detected
> 
>     * [ ]  Return something sensible, say a vector of strings of models with issues??

I think either of those are fine. If you pick option 1, I don't need to make any modifications to this PR.

If you pick option 2, I can just add `Test.@test !isempty(MLJModels.check_registry())` to this PR.

So either way it's easy for me. I'll let you pick.

**Comment by ablaom** [comment]
I'll do 2 in a new PR to continue this one now.

**Comment by ablaom** [comment]
Closed in favour of https://github.com/alan-turing-institute/MLJModels.jl/pull/370

@DilumAluthge

**Pull request closed without merging**
