### PR TITLE
GLMCount + probabilistic output

### PR DESCRIPTION
**Pull request by tlienart**
Follow up from #2 cleaned up so that

**key**

* `predict(::OLS)` outputs a vector  of Normal
* `predict(::GLMCount)` outputs a  vector of Poisson
* `predict_mean` works as pointwise predict

**minor**

* I included changes to `*.toml` files, hopefully Travis will be ok with it (looks like it is, cool!)
* metadata fixed as per comments in #2 
* waiting for a pending discussion on binary outputs etc to implement `GLMBinary` etc (with Binomial/Probit and all that jazz)

### CODE REVIEW

**Comment by ablaom** [comment]
Great but please fix your Project file conflicts. Since GLM is already in the right place ( in [extras]) all you should need to do is `]add Distributions` to the Project file on master, no?

**Comment by ablaom** [comment]
Also, do not use model aliases in `load_path`s. These must refer to the literal struct name for MLJ's @load to work properly. Thanks

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/MLJ.jl/issues/81#issuecomment-465834053

**Comment by tlienart** [comment]
Ok I think that's good to go. I kept the models separated as I think refactoring for something like `GLM{continuous}` etc should not be very hard and is probably best left for when we have a clearer vision on what is desired

**Comment by ablaom** [comment]
Great, thanks!

**Comment by ablaom** [comment]
MLJRegsitry is now updated. You should be able to:

````julia
using MLJ
@load GLMCountRegressor
````

**Pull request merged**
