### PR TITLE
Bump Distances.jl

### PR DESCRIPTION
**Pull request by juliohm**
Bumps Distances.jl to 0.10.

Also CompatHelper can be useful.

### CODE REVIEW

**Comment by ablaom** [comment]
Waiting for https://github.com/JuliaStats/Clustering.jl/pull/203 (or migration of Clustering out of MLJModels).

**Comment by devmotion** [comment]
I agree, CompatHelper might be useful, it seems Distributions compatibility should be updated as well.

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/MLJModels.jl/issues/319

**Comment by juliohm** [comment]
We can merge this now and tag a new patch release.

**Comment by ablaom** [comment]
@juliohm Thanks for patience. I will get this sorted today.

**Comment by ablaom** [comment]
Closing in favour of #325

**Pull request closed without merging**
