### PR TITLE
Add UnivariateTimeTypeToContinous - take II

### PR DESCRIPTION
**Pull request by ablaom**
continuation of #245

### CODE REVIEW

**Comment by ablaom** [comment]
The fail is due to package conflict. This request should resolve it:

https://github.com/JuliaNLSolvers/Optim.jl/pull/840#issuecomment-673877573

**Comment by ablaom** [comment]
@venuur In the tests on Julia 1.4 that run okay, there are some warnings being issued for the transformer. Be good if you can confirm they are to be expected and then I will silence them with `@test_log`s. The log is here:

https://travis-ci.com/github/alan-turing-institute/MLJModels.jl/jobs/371957210

**Comment by venuur** [comment]
Yes, the warnings are intentional. They’re the result of various data consistency checks and corrections.

________________________________

**Comment by ablaom** [comment]
Re-opening to retrigger CI

**Comment by ablaom** [comment]
We can ignore the branch fail here b/s PR test pass and the fail is due to test pkg conflict which is resolved on the base of PR.

**Pull request merged**
