### PR TITLE
XGBoost default HP num_rounds from 1 to 100

### PR DESCRIPTION
**Pull request by azev77**
num_rounds =100 is a much better default HP

### CODE REVIEW

**Comment by ablaom** [comment]
My policy is generally to match default hyperparameters to what the package documentation declares them to be, because we are not in the business of documenting the third-party models we wrap. 

@azev77 Have you checked the XGBoost docs?

**Comment by azev77** [comment]
1 `nrounds` is the only HP XGBoost doesn't provide a default value for. 
```R
library(xgboost)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test

b= xgboost(train$data,train$label)
Error in xgb.train(params, dtrain, nrounds, watchlist, verbose = verbose,  : 
  argument "nrounds" is missing, with no default

b=xgboost(train$data, train$label, nrounds = 100)
```

**Comment by ablaom** [comment]
All good then. Thanks for the clarification and this PR!

**Comment by ablaom** [comment]
Technically this is breaking, and I will hold out on merging for now. But have added it to the list #202

**Pull request merged**
