### PR TITLE
Towards 0.5.2

### PR DESCRIPTION
**Pull request by ablaom**
#64

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom @tlienart Out of curiosity, could you explain the workflow that you use with MLJ? Is it the git-flow workflow, or something different?

**Comment by ablaom** [comment]
Thanks for the query @DilumAluthge, 

I guess it is git-flow, but I don't know how strict we're. Developers now make PR's to a dev branch and with small exceptions we only merge onto master from dev and only when when a new release is to be tagged. The exceptions are non-code stuff like readme and news updates. 

I have also pushed manual updates directly to master between releases, but I as these are actually code-generated, I'm inclined to stop doing that. To be honest, we are experimenting a bit with how we do things. Suggestions welcome. 

The biggest challenge is managing several closely integrated repos, especially when we decide code in one should be migrated to another. And when we make breaking changes to MLJBase, rolling out releases for rest of the eco-system has been painful. But now auto-merge is going to fix all that, yes ? 😄

**Comment by DilumAluthge** [comment]
I don't have any suggestions to contribute, but thanks for sharing your workflow! I'm always looking to learn about new workflows to try.

**Comment by DilumAluthge** [comment]
Just FYI, currently your `[compat]` entry for Tables is `Tables = "<0.1.19, >= 0.2"`. This does not have an upper bound, so your PR will not be automerged.

**Pull request merged**
