### PR TITLE
Fix typo in docstrings of RandomForest{Regressor,Classifier}

### PR DESCRIPTION
**Pull request by Sh4pe**
Fix typo: min number... instead of max number... for RandomForestRegressor
and RandomForestClassifier

### CODE REVIEW

**Comment by Sh4pe** [comment]
The errors on Travis CI for Julia 1.0 seem to be package dependency errors ([[1]](https://travis-ci.com/github/alan-turing-institute/MLJModels.jl/jobs/388259777#L388)) and on nightly, some unit tests fail. They don't seem to be caused by my docstring changes.

**Comment by ablaom** [comment]
@Sh4pe Thanks for the fixes. I will investigate the CI failures.

**Comment by OkonSamuel** [comment]
The error also shows up silently on the MLJModels julia v1.5 tests [here](https://travis-ci.com/github/alan-turing-institute/MLJModels.jl/jobs/388259778#L410)

**Comment by ablaom** [comment]
I've started investigating. Hopefully #308 will fix. 🤞

**Comment by ablaom** [comment]
See also: https://github.com/dfdx/NaiveBayes.jl/pull/44

**Comment by ablaom** [comment]
Okay, it seems #308 will fix the silent fail but not the julia 1.0 fail, which probably needs the NaiveBayes PR.

**Review by OkonSamuel — APPROVED** [review]

**Pull request merged**
